### ISSUE TITLE
Thread starter avatar is not working

### ISSUE THREAD

**Issue by Eldenroot** [dragonexpert/recentthreads#74]
![image](https://user-images.githubusercontent.com/778890/104355790-745a2c80-550b-11eb-8944-b18ba4502344.png)

**Comment by dragonexpert** [comment]
This is fixed now.

**Comment by Eldenroot** [comment]
I dont think so - for unregistered users both avatars are not displayed (v20).

**Comment by dragonexpert** [comment]
That is intentional.  There would not be a way to do a per user so it would be either all or none.  I'd rather it be no guests can view it because this way it limits the amount of bandwidth you are using and lowers how much data they are using since they would have no control over avatars appearing.  Cookies would not be a solution because there are no guarantees they will accept cookies since they are a guest and not a logged in user.

**Comment by Eldenroot** [comment]
But it is possible already, for example Last post avatar plugin can display all avatars even for unregistered users...

**Comment by dragonexpert** [comment]
It probably doesn't actually check what user settings are though.  It is better to error on the side of caution than to possibly overwrite permissions.
